---
- hosts: testserver

  roles:
     - start_services
     - turnoff_selinux
     - variables_from_shell
     - full_update
     - packages_removal
     - user_creation
     - user_creation_sudo
     - add_firewall
     - ssh_config
#    - root_password
     - reload_services
