- name: NGINX | Installing NGINX repo rpm
  yum:
    name: epel-release
 
- name: NGINX | Installing NGINX
  yum:
    name: nginx
    state: latest

- name: NGINX | Make Conf.d dir
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: NGINX | Add Default UT Config file
  become: true
  template:
    src: "{{ src_config }}"
    dest: "{{ dest_config }}"
 
- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started
