- name: Creating sshuser-group
  group:
    name: sshuser
    state: present

- name: Creating users
  become: true
  user: name={{ item.value.name }} password={{ item.value.password |password_hash('sha512') }} groups=sshuser
  with_dict: "{{ users }}"
  tags: usercreation
  

- name: Creating .ssh dir-file
  become: true
  file:
    path: /home/{{ item.value.name }}/.ssh
    state: directory
    owner: "{{ item.value.name }}"
    group: "{{ item.value.name }}"
    mode: 0777
  with_dict: "{{ users }}"
  tags: userdircreation

- name: Creating .ssh/authorized_keys file
  become: true
  become_user: "{{ item.value.name }}"
  template:
    src: /home/makinglaugh/.ssh/id_rsa.pub
    dest: "/home/{{ item.value.name }}/.ssh/authorized_keys"
  with_dict: "{{ users }}"
  tags: userdircreation

- name: chmod files
  become: true
  shell: chmod -R 640 /home/{{ item.value.name }}/.ssh && chown -R {{ item.value.name }}:{{ item.value.name }} /home/{{ item.value.name }}/.ssh && chmod 700 /home/{{ item.value.name }}/.ssh
  with_dict: "{{ users }}"
  tags: userdircreation
